{
    "name": "Evo Casa Hr Enhancement",
    "summary": """Casa Hr Enhancement For Odoo 14""",
    "description": """Odoo 14.0 Casa Hr Enhancement""",
    "author": "",
    "website": "",
    "category": "HR expense",
    "version": "1.0",
    "depends": ["hr_expense"],
    "data": ["views/hr_expense_sheet_view.xml",],
    "qweb": [],
    "images": [],
    "auto_install": False,
    "installable": True,
    "application": True,
}
